### PR TITLE
Fix collisions

### LINKED ISSUE #130: Collisions do not happen at the correct point
Fish can collide when they do not overlap at all, resulting in unfair deaths.

### PR DESCRIPTION
**Pull request by Taeir**
Fixes pixel perfect collisions and box intersections.
Fixes powerups counting towards the max enemies.

This fixes #130

<bug,testing

### CODE REVIEW

File: src/main/java/com/github/fishio/BoundingBox.java [hunk 1]
```diff
@@ -23,9 +23,12 @@
...
 	public BoundingBox(double xmin, double ymin, double xmax, double ymax) {
-		this.width = xmax - xmin;
-		this.height = ymax - ymin;
-		this.center = new Vec2d(xmin + 0.5 * width, ymin + 0.5 * height);
+		this.width = Math.abs(xmax - xmin);
+		this.height = Math.abs(ymax - ymin);
+		
+		double xxMin = Math.min(xmin, xmax);
+		double yyMin = Math.min(ymin, ymax);
+		this.center = new Vec2d(xxMin + 0.5 * width, yyMin + 0.5 * height);
```
Comment (ChielBruin) [inline src/main/java/com/github/fishio/BoundingBox.java:31]: It would be better readable to name these variables just xmin and ymin. 
It wouldn't break the code.
<naming

File: src/main/java/com/github/fishio/ICollisionArea.java [hunk 2]
```diff
@@ -19,25 +17,33 @@
...
-		AffineTransform t1 = new AffineTransform();
-		AffineTransform t2 = new AffineTransform();
+		Rectangle myBox = getBox();
+		Rectangle otherBox = other.getBox();
 		
-		t1.rotate(Math.toRadians(this.getRotation()), 
-				this.getCenterX(), this.getCenterY()); //rotate self
-		t2.rotate(Math.toRadians(other.getRotation()), 
-				other.getCenterX(), other.getCenterY()); //rotate around other
+		return myBox.intersects(otherBox.getBoundsInParent());
```
Comment (ChielBruin) [inline src/main/java/com/github/fishio/ICollisionArea.java:23]: This is a lot easier!
<feature

File: src/test/java/com/github/fishio/TestICollisionArea.java [hunk 3]
```diff
@@ -11,6 +11,7 @@
  */
 public abstract class TestICollisionArea {
 	
+	private static final double DELTA = 1E-12;
```
Comment (ChielBruin) [inline src/test/java/com/github/fishio/TestICollisionArea.java:14]: :+1: 
<naming,layout

File: src/main/java/com/github/fishio/BoundingBox.java (hunk 1 above)
Comment (Taeir) [inline src/main/java/com/github/fishio/BoundingBox.java:31]: It would, xmin and ymin are already used as parameters

<naming

**Comment by ChielBruin** [comment]
It looks good!
The code has become simpler and better.
I made one comment on the naming of variables, but after that is resolved I vote for a merge!

<review

**Comment by Diocruel** [comment]
Nice! I looked over the code and it looks good.

Merging.

<review, bug
